### ISSUE TITLE
Criar diagrama de classe

### ISSUE THREAD

**Issue by gabrielcardelli** [w2br/worldcup2018#4]
Definir as classes que farão parte do modelo do sistema.

**Comment by arilnayak** [comment]
![wc18 - page 1](https://cloud.githubusercontent.com/assets/26308588/23826979/b6b93638-0687-11e7-8739-d7080fb17029.png)

**Comment by arilnayak** [comment]
Modelo 2.0

![modelo2 0](https://cloud.githubusercontent.com/assets/26308588/23996017/b72da2f6-0a2a-11e7-9770-da887c0884be.png)
